keys:
  - &users:
    - &sivak age10rvpnvdd0gzhrvgmzzd3l033w4pgevwdquctpn82r3mfrhslqfnqvcguvt # ~/.ssh/
  - &hosts:
    - &nixos age1v5zqdn64ascrtsahwd95tzp48mghcuzf9evtwkt0ny99f88fk3sqjdmchj # /etc/ssh
    - &server age1ew9sa35c47lqxrdw3k8aaa0ucc38wscwdytds6de6y4upp7kvcas492l8p # /etc/ssh
    - &laptop age13vrhqtd3ljwxvnqh7662f0d65e8m05lll6dtmgvzms4d9mw87efqcjyn9s # /etc/ssh
    - &vps age1ttz8fgx48yw2z0smcker2ltch95a3neh8mq608dv9hdtqup37evqmaue6f # /etc/ssh
  - &masterkey age1d5kndnmdhvqsg9l2pe8a692jll2ugfyyx3vtteqwsrn32a2elp8qlhy4yj
creation_rules:
  - path_regex: secrets/global.yaml
    key_groups:
      - age:
        - *sivak
        - *nixos
        - *server
        - *laptop
        - *masterkey
    
  - path_regex: secrets/hosts/laptop\.yaml
    key_groups:
      - age:
          - *laptop
          - *masterkey

  - path_regex: secrets/hosts/nixos\.yaml
    key_groups:
      - age:
          - *nixos
          - *masterkey
          
  - path_regex: secrets/hosts/server\.yaml
    key_groups:
      - age:
          - *server
          - *masterkey

  - path_regex: secrets/users/sivak\.yaml
    key_groups:
      - age:
          - *sivak
          - *masterkey

  - path_regex: secrets/etc/mail\.yaml
    key_groups:
      - age:
          - *vps
          - *server
          - *masterkey

  - path_regex: secrets/etc/cloudflare\.yaml
    key_groups:
      - age:
          - *vps
          - *server
          - *masterkey
