keys:
  - &users:
    - &sivak age10rvpnvdd0gzhrvgmzzd3l033w4pgevwdquctpn82r3mfrhslqfnqvcguvt # ~/.ssh/
  - &hosts:
    - &nixos age1v5zqdn64ascrtsahwd95tzp48mghcuzf9evtwkt0ny99f88fk3sqjdmchj # /etc/ssh
    - &server age1ew9sa35c47lqxrdw3k8aaa0ucc38wscwdytds6de6y4upp7kvcas492l8p # /etc/ssh
    - &laptop age13vrhqtd3ljwxvnqh7662f0d65e8m05lll6dtmgvzms4d9mw87efqcjyn9s # /etc/ssh
    - &vps age1ettvfqs720wq25nmk2ghd7jh33w9q2rf0dhg843q0g8ms9gegawswduwf0 # /etc/ssh
    - &node age1jcdj6hdd2f3vdntwquajr7gn43fqqld5ha42afv3vpen47qz0sxsfm9gpg # /etc/ssh
  - &masterkey age1d5kndnmdhvqsg9l2pe8a692jll2ugfyyx3vtteqwsrn32a2elp8qlhy4yj
creation_rules:
  - path_regex: secrets/global.yaml
    key_groups:
      - age:
        - *node
        - *sivak
        - *nixos
        - *server
        - *laptop
        - *masterkey
    
  - path_regex: secrets/users/sivak\.yaml
    key_groups:
      - age:
          - *sivak
          - *masterkey

  - path_regex: secrets/etc/mail\.yaml
    key_groups:
      - age:
          - *vps
          - *server
          - *masterkey

  - path_regex: secrets/etc/cloudflare\.yaml
    key_groups:
      - age:
          - *node
          - *vps
          - *server
          - *masterkey
  - path_regex: secrets/etc/vikunja\.yaml
    key_groups:
      - age:
          - *node
          - *masterkey
  - path_regex: secrets/etc/vaultwarden\.yaml
    key_groups:
      - age:
          - *node
          - *masterkey
