keys:
  - &users:
    - &sivak age10rvpnvdd0gzhrvgmzzd3l033w4pgevwdquctpn82r3mfrhslqfnqvcguvt
  - &hosts:
    - &nixos age1v5zqdn64ascrtsahwd95tzp48mghcuzf9evtwkt0ny99f88fk3sqjdmchj
    - &server age12jvsw5cvary6nx3tug94f9u7wnj6tgh7nf8hpl8dxnlaug5h7a5svuzuqt
    - &laptop age13vrhqtd3ljwxvnqh7662f0d65e8m05lll6dtmgvzms4d9mw87efqcjyn9s
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *sivak
        - *nixos
        - *server
        - *laptop
