keys:
  - &users:
    - &sivak age10rvpnvdd0gzhrvgmzzd3l033w4pgevwdquctpn82r3mfrhslqfnqvcguvt # ~/.ssh/
  - &hosts:
    - &nixos age1v5zqdn64ascrtsahwd95tzp48mghcuzf9evtwkt0ny99f88fk3sqjdmchj # /etc/ssh
    - &server age12jvsw5cvary6nx3tug94f9u7wnj6tgh7nf8hpl8dxnlaug5h7a5svuzuqt # /etc/ssh
    - &laptop age13vrhqtd3ljwxvnqh7662f0d65e8m05lll6dtmgvzms4d9mw87efqcjyn9s # /etc/ssh
  - &masterkey age1d5kndnmdhvqsg9l2pe8a692jll2ugfyyx3vtteqwsrn32a2elp8qlhy4yj
creation_rules:
  - path_regex: global.yaml
    key_groups:
      - age:
        - *sivak
        - *nixos
        - *server
        - *laptop
        - *masterkey
    
  - path_regex: hosts/laptop\.yaml
    key_groups:
      - age:
          - *laptop
          - *masterkey

  - path_regex: hosts/nixos\.yaml
    key_groups:
      - age:
          - *nixos
          - *masterkey
          
  - path_regex: hosts/server\.yaml
    key_groups:
      - age:
          - *server
          - *masterkey

  - path_regex: users/sivak\.yaml
    key_groups:
      - age:
          - *sivak
          - *masterkey

  - path_regex: etc/mail\.yaml
    key_groups:
      - age:
          - *server
          - *masterkey
